export const FETCH_POSITIONS_START = 'FETCH_POSITIONS_START';
export const FETCH_POSITIONS_SUCCESS = 'FETCH_POSITIONS_SUCCESS';
export const FETCH_POSITIONS_ERROR = 'FETCH_POSITIONS_ERROR';

export const SEND_USER_START = 'SEND_USER_START';
export const SEND_USER_SUCCESS = 'SEND_USER_SUCCESS';
export const SEND_USER_ERROR = 'SEND_USER_ERROR';

export const FETCH_TOKEN_START = 'FETCH_TOKEN_START';
export const FETCH_TOKEN_SUCCESS = 'FETCH_TOKEN_SUCCESS';
export const FETCH_TOKEN_ERROR = 'FETCH_TOKEN_ERROR';
